### ISSUE TITLE
information

### ISSUE THREAD

**Issue by gtortone** [komw/ariston-bus-bridgenet-ebusd#1]
Hi,
which kind of eBusd adapter are you using ?

I have Ariston Genus Premium EVO that is based on BridgeNET protocol,
and I was wondering how to start to use eBusd with my boiler...

Thanks in advance,
Gennaro

**Comment by komw** [comment]
Please loot at https://ebusd.eu/ there is a few examples of ebus adapters. Currently I'm using a 2.2 version with attached orange pi zero plus as a UART+ebusd daermon.
Hard to say if it will work with Genus Premium EVO. I'm using a Ariston Genus One with attached a Cube S Net thermostat, and this configuration works without problems.

**Comment by brusuillis** [comment]
HI all, I have a Ariston Genus One Flex (Hybrid + Water Tank). It is "working" with this setup but I only get 11 values out of what I think could be 100...
Also, some of them don't seem to be correct (probably due to different setup).
Can somebody point me to reverse engineering the messages and "update" my version of the .csv?

**Comment by komw** [comment]
> HI all, I have a Ariston Genus One Flex (Hybrid + Water Tank). It is "working" with this setup but I only get 11 values out of what I think could be 100...
> Also, some of them don't seem to be correct (probably due to different setup).
> Can somebody point me to reverse engineering the messages and "update" my version of the .csv?

You need to read the Ebusd documentation https://github.com/john30/ebusd/wiki Its not so easy to find the values, in most cases it means that you need to watch at some addresses in communication, and try to compare the values with the values in service menu of your boiler. You need to start with reading whole documentation of ebus carefully.
