### ISSUE TITLE
Pump max and min pwm

### ISSUE THREAD

**Issue by VoyteckPL** [komw/ariston-bus-bridgenet-ebusd#10]
Hi,
These settings in Ariston Genus One are adjustable so this can be "write" as well.
How do I create these lines as write?

r,boiler,pump_max_pwm,Pump Max PWM,,3c,2000,c928,,s,IGN:1,,,,,s,UCH,,pct
r,boiler,pump_min_pwm,Pump Min PWM,,3c,2000,ca28,,s,IGN:1,,,,,s,UCH,,pct

**Comment by komw** [comment]
Please create a Pull Request for it, and then I'll merge it

**Comment by VoyteckPL** [comment]
Sorry, I don't know how to do it?
I copied the "r" lines from ariston.csv and now I don't know how to create "w" lines. :/

**Comment by komw** [comment]
Please refer to this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

You need a simple create a fork of the repo, create a branch with the changes, and then put a pull request so I'll be able to merge your changes to the code.

**Comment by VoyteckPL** [comment]
The problem is that I don't know how to create "w" lines for these parameters

**Comment by komw** [comment]
ah. ok, 
Hard to say, I dont know what Ids of that vaules you need to change,
Did you tried to do a write like any other fields?

**Comment by VoyteckPL** [comment]
yes but I did unexpected results. Not sure how to create the write lines.
