### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by brusuillis** [komw/ariston-bus-bridgenet-ebusd#4]
Hi @komw , I know it has passed some time since you developed it, but I'm just setting it up with an Ariston Genux Flex Net Hybrid.
I receive 19 topics from the mqtt attached to the busd, but I'm SURE there is more (the whole Heat Pump, for example). Can you point me in how to start "sniffing" the bus for those messages that are not recognized by your csv?

Thanks

**Comment by komw** [comment]
i'm pretty sure that there is much more information in ebus communication. But I didn't have much time to spend to debugging it, so I only found values which was interesting for me.
Also if you are using a different heater (I'm using a Genus One Net), the addresses for specific values could be different.
