### ISSUE TITLE
Config for Ariston Clas One

### ISSUE THREAD

**Issue by nofoxgit** [komw/ariston-bus-bridgenet-ebusd#8]
I have eBus adapter v5 and Ariston Clas One. Config for Genus One working partially... There are many "received unknown BC cmd:" And also the temperature values are all multiply by 10.  Can we contact (in polish ;) ) to work this around ?

**Comment by komw** [comment]
Here will be better to use English as it will be easier for other users. 
The values are multiply by 10 because it's easier to parse the integer values than float. 
"Received unknown BC CMD" message means that not all messages on bus are parsed. There is many messages for I couldn't find meaning, so not everything is parsed.
if you like to contact me in polish please use direct message :)

**Comment by nofoxgit** [comment]
There are no direct message option on GitHub i think..

**Comment by komw** [comment]
So please drop here your question :)

**Comment by wrongisthenewright** [comment]
I have expanded a little the komw ebusd configuration. My appliance is an hybrid system with HP+boiler.
Try my file and check if some of the codes I was able to decode apply also to your boiler.

You can find it here:
https://github.com/wrongisthenewright/ebusd-configuration-ariston-bridgenet

You can also take a look at ysard repo where it reports some other codes he's been able to gather.

https://github.com/ysard/ebusd_configuration_chaffoteaux_bridgenet

Hope it helps

**Comment by komw** [comment]
Thank a lot!!

**Comment by nofoxgit** [comment]
Thanks! The thing is that now when I load komws ariston.cvs config I'm getting only values that are specified in '#direct ask'.. How do you sniff for other values ? What I need the most is to read burner power a write temperature set point and heating curve (slope?).

**Comment by nofoxgit** [comment]
> I have expanded a little the komw ebusd configuration. My appliance is an hybrid system with HP+boiler. Try my file and check if some of the codes I was able to decode apply also to your boiler.
> 
> You can find it here: https://github.com/wrongisthenewright/ebusd-configuration-ariston-bridgenet
> 
> You can also take a look at ysard repo where it reports some other codes he's been able to gather.
> 
> https://github.com/ysard/ebusd_configuration_chaffoteaux_bridgenet
> 
> Hope it helps

When I load your file I get error "ariston.csv:62 wrong element" or something like that and only EWT_temp are transmitted...

**Comment by komw** [comment]
For some of the values you simple need to wait as it is send as broadcast messages from thermostat or boiler, and you need to wait for the message. For some values you need to wait hours.. 

You can force it by changing the value manually.
You can check if the config is proper by send your own value to that field. If the config is correct the boiler will resend this value as broadcast. Also you can trigger it by changing the settings in boiler or thermostat.

You need to notice that slope config was changed comparing to other ariston repositories as it wasn't work for my ariston genus one.

**Comment by nofoxgit** [comment]
OK, now I see, in @wrongisthenewright config the problem is 'onoff' value at the end of few lines. Now I get no errors at startup.

**Comment by wrongisthenewright** [comment]
For the onoff problem you need to put into the configuration folder the _template.csv file.

For the other issues you need to study how ebusd works and how the CSV file is formatted.

It's not a plug&play software, it's a precarious and complicated system with many pieces that needs to work together.

**Comment by nofoxgit** [comment]
I've found conversation on elektroda forum where someone use c404 address to fetch boiler power, the address is valid but it returns 0 no matter if the boiler is in heating state or not. I think that if we can read nominal power, and max and min power there must be actual power somewhere ;)

**Comment by komw** [comment]
Of course it should be available, but it's no easy way to find it, so feel free to debug messages and try to find out which exactly is actual power

**Comment by wrongisthenewright** [comment]
> Thank a lot!!

Komw, I'd be thankful if you'd put some credits on your repo linking my repo. It's not for me but for the other guys that helped me find many codes and helped me setting up writing rules.

Ty & happy new year

**Comment by komw** [comment]
I think that better idea is to merge all changes and put it into one repository.  I have no idea why is better to have few repositories  with almost the same ebus codes, etc. Much better is to improve one, use PR for it, and have one place to get all info about how it work :)

**Comment by nofoxgit** [comment]
I have found somewhere that c104 is burner power value. 
added this: r,boiler,actual_power,Actual Power,,3c,2000,c104,ign,s,IGN:1,,,,,s,UCH,,kW
and indeed it looks like power but its not in kW or maybe it should be divided by 10 or maybe its in % ? 

When DHW mode is on the value gets 237 
When CH heating is on the value starts around 120 - 140 and slowly goes down to 50 - 40 before flame cutoff.
